name: PR Number

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: gh pr comment $PR_NUMBER --body "Thank you for your contribution"
        
