name: PR Number

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER
          echo $PR_NUMBER > ./pr/pr_number
